### ISSUE TITLE
Support Spring Cloud Finchley.RELEASE

### ISSUE THREAD

**Issue by Hanson1330** [Nepxion/Discovery#1]
有支持Finchley.RELEASE的计划吗？

**Comment by Nepxion** [comment]
F版本只兼容Spring Boot 2.0版本，不敢轻易尝试，你可以试试看，升级spring-boot-starter-parent到2.0.1.RELEASE，升级spring-cloud-dependencies到Finchley.RELEASE

**Comment by Nepxion** [comment]
今天Spring Cloud从E版本升级到F版，踩了许多坑，后来决定“暂时”不支持F版本，坑如下：
1. pom引入的id都变了，很多需要加netflix
2. 很多原先@Deprecated的代码全部被删除掉了
3. 很多原先较常用的类也都被删除了
4. 很多类所在包的包名改了，甚至类名也改了
5. 特别不爽的是，Spring Boot Actuator的Endpoint完全和以前不一样了，以前用法和RestController一直，现在变成
https://spring.io/blog/2017/08/22/introducing-actuator-endpoints-in-spring-boot-2-0

**Comment by Nepxion** [comment]
完美支持 C版、D版、E版和F版本，如下：
Spring Cloud F版，请采用4.x.x版本，具体代码参考master分支
Spring Cloud C版、D版和E版，请采用3.x.x版本，具体代码参考Edgware分支
详情请参考首页

**Comment by Nepxion** [comment]
请加我微信 1394997，详细探讨

**Comment by ExtremeYu** [comment]
大佬，此项目必火
