### ISSUE TITLE
Console Desktop服务不支持配置server.servlet.context-path

### ISSUE THREAD

**Issue by zhaipan** [Nepxion/Discovery#10]
当给服务配上server.servlet.context-path 后，Console Desktop服务调用其他服务的接口没能自动带上contextpath
详细异常信息
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://10.0.5.16:8769/router/routes": http://10.0.5.16:8769/router/routes; nested exception is java.io.FileNotFoundException: http://10.0.5.16:8769/router/routes

**Comment by Nepxion** [comment]
desktop在config目录下有个配置文件，里面地址指向控制台console的地址，只是简单的rest请求而已

**Comment by zhaipan** [comment]
抱歉，我之前的表述有点问题，我想说的是example-zuul和example-service这两个服务如果配上server.servlet.context-path项目名，console-Desktop和example-console就会出问题，在console-Desktop里操作执行灰度路由会报错：org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://10.0.5.16:8769/router/routes": http://10.0.5.16:8769/router/routes; nested exception is java.io.FileNotFoundException: http://10.0.5.16:8769/router/routes  。  表现为请求地址url错误，应该是加上项目名的 http://10.0.5.16:8769/xxxx/router/routes

**Comment by Nepxion** [comment]
我明白你的意思了，但我想了解，你们这么做主要是什么场景？

**Comment by Nepxion** [comment]
你可以扫描主页的微信二维码，进去到我群里去，我们跟大伙一起讨论一下你的需求

**Comment by Nepxion** [comment]
今天在群里讨论了一下你的方案，首先，几乎没有公司加context-path，其次，改动比较大，所有的rest api都要加一遍，暂时不支持了，但是不影响主体灰度发布功能。个人建议，供你参考：
1. 取消掉context-path，改加在头部的RequestMapping。说实话，context-path加在外面，我没体会到好处，反而有危害，配置文件中，那个地方被人为修改，下游服务的rest调用立马全部挂掉

2. 我不清楚，你们是否用Feign，这个配置对Feign来说，也是个坑。参考https://segmentfault.com/q/1010000014431631/a-1020000014648560

3. 我不清楚，你们是否用监控之类的，也是个坑。参考https://blog.csdn.net/hubo_88/article/details/80684339

4.我不清楚，你们是否用Endpoint，这个配置会让增加路径的复杂性。参考https://www.cnblogs.com/yangfei-beijing/p/6379258.html

**Comment by Nepxion** [comment]
你的需求已经支持，请更新最新代码

**Comment by zhaipan** [comment]
非常感谢您的回复和指点，我的问题已经解决了，您说的没错，context-path会带来很多问题，我已经不再使用context-path配置了。我的应用场景是的将一个传统的web项目改造成微服务，由于资源限制，用的thymeleaf模板做页面端处理，没有用vue、angular等前端技术做前后端分离开发，搭配zuul网关后每个web微服务都有路径错乱的问题发生。用于不用context-path都有这样的问题。再次非常感谢您的回复。

**Comment by Nepxion** [comment]
嗯，昨天我花了三个小时时间改了大量代码，也支持了context-path的方案，其实你的需求也是合理的
