### ISSUE TITLE
路由规则里strategy-customization->conditions区域是否支持通配符

### ISSUE THREAD

**Issue by Roger535** [Nepxion/Discovery#102]
`<rule>
    <strategy-customization>
        <conditions type="blue-green">
            <condition id="condition1" header="#H['namespace'] == 'a-system' && #H['domain'] == 'green'" version-id="route1"/>
            <condition id="condition2" header="#H['namespace'] == 'a-system' && #H['domain'] == 'blue'" version-id="route2"/>
        </conditions>
		
        <conditions type="gray">
            <condition id="condition1" header="#H['namespace'] == 'a-system'" version-id="route1=90;route2=10"/>
            <condition id="condition2" header="#H['namespace'] == 'b-system'" version-id="route3=80;route4=20"/>
        </conditions>		

        <routes>
            <route id="route1" type="version">{"discovery-guide-service-a":"1.0", "discovery-guide-service-b":"1.0"}</route>
            <route id="route2" type="version">{"discovery-guide-service-a":"2.0", "discovery-guide-service-b":"2.0"}</route>
            <route id="route3" type="version">{"discovery-guide-service-c":"1.0", "discovery-guide-service-d":"1.0"}</route>
            <route id="route4" type="version">{"discovery-guide-service-c":"2.0", "discovery-guide-service-d":"2.0"}</route>			
        </routes>
    </strategy-customization>
</rule>`
`http_user_agent:  Mozilla/5.0 (Linux; Android 10; TAS-AL00 Build/HUAWEITAS-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.62 XWEB/2461 MMWEBSDK/200502 Mobile Safari/537.36 MMWEBID/696 MicroMessenger/7.0.15.1680(0x27000F3D) Process/tools WeChat/arm64 NetType/4G Language/zh_CN ABI/arm64`
比如我要匹配http_user_agent里的Android需要怎么设置，谢谢
header="#H['http_user_agent'] == '*Android*'" 试了好像不行

**Comment by HaojunRen** [comment]
这是Spring的Spel语法，似乎不支持通配符，请自行研究一下
