### ISSUE TITLE
文档错误，并请教一下 gray、blue-green

### ISSUE THREAD

**Issue by gujiachun** [Nepxion/Discovery#105]
<strategy-customization>
        <conditions>
            <condition id="condition1" header="a=1" version-id="version-route1"/>
            <condition id="condition2" header="a=2" version-id="version-route2"/>
        </conditions>

        <routes>
            <route id="version-route1" type="version">{"discovery-guide-service-a":"1.0", "discovery-guide-service-b":"1.0"}</route>
            <route id="version-route2" type="version">{"discovery-guide-service-a":"1.1", "discovery-guide-service-b":"1.1"}</route>
        </routes>
    </strategy-customization>
案例中上面的xml配置，网关解析失败，因为conditions缺少type属性；作者可以更新一下文档。

在请教一下gray和blue-green方式的区别，已经应用场景；没有看到文档上面有说明

谢谢！！！

**Comment by gujiachun** [comment]
还有个问题就是，在header传入参数a=2，没有达到预期的效果 调用1.1版本；；；不管a参数是什么值，一直是1.0版本

**Comment by HaojunRen** [comment]
1. 文档错误，我似乎没找到错误的地方，请指正具体在哪里，或者你使用的是老的版本的文档？
2. gray表示灰度发布，blue-green表示蓝绿发布，前者是流量百分比调拨的概念，后者是两套环境，流量要么到蓝环境，要么到绿环境
3. 第三个问题，应该定位在使用问题上，请仔细检查配置或者阅读说明

**Comment by gujiachun** [comment]
谢谢，确实文档不对。我看的是 指南那边的文档https://www.cnblogs.com/Alandre/p/11649111.html
