### ISSUE TITLE
只想要灰度路由策略功能，而不想要灰度发布功能

### ISSUE THREAD

**Issue by gujiachun** [Nepxion/Discovery#106]
请问一下作者，灰度路由策略 和 灰度发布功能 主要区别是什么。

我的理解就是 在配置文件中 配置
<strategy>......</strategy>这个里面代表路由策略

< discovery>...</discovery>这个里面代表发布功能

请问一下 怎么理解灰度路由策略 和 灰度发布功能

非常感谢，一直没弄明白

**Comment by HaojunRen** [comment]
文章中提到的，灰度路由是通过Header的全链路传递实现灰度功能，灰度发布是所有的服务共同订阅配置中心的灰度配置实现灰度功能（狭义的灰度发布）。相对来说，路由更灵活，实时性更好，还可以和业务自身的Header整合在一起，实现更高级的组合式灰度功能

**Comment by gujiachun** [comment]
谢谢，那路由策略是不是只要通过网关gateway ，去订阅nacos中的远程配置中的路由规则 dataid 为gateway的名称就行了吧。

灰度发布 就是所有服务 去订阅 dataid为group的名称

**Comment by HaojunRen** [comment]
基本准确。但纠正一点，路由策略不仅可以在网关上触发，也可以在服务上触发。因为网关只是一个特殊的微服务而已

**Comment by gujiachun** [comment]
谢谢
