### ISSUE TITLE
如何去掉启动时控制台打印的banner？

### ISSUE THREAD

**Issue by kanghouchao** [Nepxion/Discovery#108]
如题

**Comment by HaojunRen** [comment]
System.setProperty(BannerConstant.BANNER_SHOWN, "false");

**Comment by HaojunRen** [comment]
import com.nepxion.banner.BannerConstant;

public class BannerApplicationContextInitializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {
    @Override
    public void initialize(ConfigurableApplicationContext applicationContext) {
        if (!(applicationContext instanceof AnnotationConfigApplicationContext)) {
            System.setProperty(BannerConstant.BANNER_SHOWN, "false");
        }
    }
}

**Comment by kanghouchao** [comment]
OK了，十分感谢
