### ISSUE TITLE
请求头传递

### ISSUE THREAD

**Issue by kanghouchao** [Nepxion/Discovery#110]
我使用的是6.0.5版本，网关用的是gateway, 注册中心和配置中心用nacos

关于：spring.application.strategy.business.request.headers和spring.application.strategy.context.request.headers
这两个配置是一样的吧？我看源码他们两个是被加载到同一个集合里面的

我在配置文件里面配置了，在项目启动能看到关于这个配置参数的日志打印

但是配置的请求头没有被传递到后面的服务，即feign调用没有根据请求头选择不同的路线

**Comment by kanghouchao** [comment]
nacos基础配置（所有项目中有效）：
`spring.application.strategy.context.request.headers=token;dept-id`

前端在请求头中添加参数:
`dept-id=1`

全局灰度规则:
`
<?xml version="1.0" encoding="UTF-8"?>
<rule>
  <discovery>
    <strategy-customization>
      <conditions type="blue-green">
            <condition id="1" header="#H['dept-id`'] == '1'" version-id="a-1"/>
            <condition id="2" header="#H['dept-id`'] != '1'" version-id="a-2"/>
        </conditions>
        <routes>
            <route id="a-1" type="version">{"server-a":"1.0"}</route>
            <route id="a-2" type="version">{"server-a":"2.0"}</route>
        </routes>
    </strategy-customization>
  </discovery>
</rule>
`

**Comment by kanghouchao** [comment]
查看源码在 FeiginStrategyInerceptor 这个拦截器中调用的并未使用到配置在headers中参数，有两个方法因为没有打开debug所有没有被调用，但是就算调用我看里面也只是打印了请求头信息，而且因为contextHolder无法获取到attributes而不会起作用

**Comment by kanghouchao** [comment]
请求从前端，我测试的时候用的postman，到网关，a服务，b服务

当我把路由策略中server-b改为server-a，那么网关到a服务是可以完成蓝绿访问的
但是当策略中配置的是server-b，那么a服务feign调用b服务的时候没有蓝绿访问效果
打开feign日志，请求头中间没有dept-id字段

**Comment by HaojunRen** [comment]
Q: spring.application.strategy.business.request.headers和spring.application.strategy.context.request.headers
这两个配置是一样的吧
A: 作用一样

用法是可能存在问题

"#H['dept-id`'] == '1'"，多了一个`？

**Comment by kanghouchao** [comment]
那个符号问题是我在录入问题的时候不小心多输入的

**Comment by kanghouchao** [comment]
添加了依赖
```xml
<dependency>
    <groupId>com.nepxion</groupId>
    <artifactId>discovery-plugin-strategy-starter-hystrix</artifactId>
    <version>${discovery.version}</version>
</dependency>
```
再添加配置
`spring.application.strategy.hystrix.threadlocal.supported=true`

问题解决
