### ISSUE TITLE
麻烦解释下【灰度发布】的含义

### ISSUE THREAD

**Issue by janecms** [Nepxion/Discovery#111]
> 灰度发布。基于规则订阅的全链路灰度发布，包括切换发布（版本匹配发布、区域匹配发布）和平滑发布（版本权重发布、区域权重发布）
灰度路由。基于Header传递的全链路灰度路由，包括切换路由（版本匹配路由、区域匹配路由、机器IP和端口匹配路由）和平滑路由（版本权重路由、区域权重路由）。可以在网关过滤器、前端界面、负载均衡策略类三个地方实现路由功能

文档里说的灰度发布，是什么意思？单独说灰度发布，有意义吗？指的是什么？ 所谓的权重，匹配只有在路由的时候才有实际效果。

文档很丰富，但给人感觉，这也看不懂，那也看不懂。术语满天飞。

**Comment by HaojunRen** [comment]
切换灰度（也叫刚性灰度）和平滑灰度（也叫柔性灰度），切换灰度即在灰度的时候，没有过渡过程，流量直接从旧版本切换到新版本；平滑灰度即在灰度的时候，有个过渡过程，可以根据实际情况，先给新版本分配低额流量，给旧版本分配高额流量，对新版本进行监测，如果没有问题，就继续把旧版的流量切换到新版本上
