### ISSUE TITLE
线程代理 Aysnc 无法传递灰度

### ISSUE THREAD

**Issue by wushengqiang** [Nepxion/Discovery#112]
在springboot中启用了@EnableAsync 注解后,灰度链路不能正常的传递到异步线程中,不启用这个注解,则可以传递

**Comment by HaojunRen** [comment]
加DiscoveryAgent解决异步问题，请参考在文档里寻找一下

**Comment by wushengqiang** [comment]
我用的是文档中的 discovery-plugin-strategy-starter-agent-6.0.6.jar 这个来代理的,-Dthread.scan.packages也设置了org.springframework.aop.interceptor这个包名,但是开启@EnableAsync  这个之后,还是无法传递灰度信息

**Comment by HaojunRen** [comment]
三个全部都加上吧

**Comment by wushengqiang** [comment]
-javaagent:G:/download/discovery-agent/discovery-plugin-strategy-starter-agent-6.0.6.jar
-Dthread.scan.packages=com.sz7road.tech.sdk;org.springframework.aop.interceptor
-Dthread.request.decorator.enabled=true   我是这样设置的

**Comment by HaojunRen** [comment]
启动参数里设置进去了么？agent生效会在控制台打印出来的

**Comment by wushengqiang** [comment]
![image](https://user-images.githubusercontent.com/11436479/93324872-0b0e2980-f849-11ea-8242-1cb1d67371fc.png)
我看agent是生效了

**Comment by HaojunRen** [comment]
你代码跟到agent里面去看看，debug一下，我测试过，运行正常的

**Comment by HaojunRen** [comment]
问题是否解决？

**Comment by wushengqiang** [comment]
通过Agent线程代理的方式还是无法解决@EnableAsync  注解后的spring异步,我自己通过使用线程池TaskDecorator 的方式解决了
![image](https://user-images.githubusercontent.com/11436479/93411142-12771680-f8cd-11ea-82eb-a1c9f6dd8aa0.png)

**Comment by HaojunRen** [comment]
你的实现方式和Agent实现方式逻辑是一样的

**Comment by wushengqiang** [comment]
是的,和业务有点耦合

**Comment by zifeihan** [comment]
@wushengqiang 兄弟，这个原因在于lambda实现的接口并不会触发类加载动作。经过调研，我们这个DiscoveryAgent是基于Spring 4.x而研发的，在这个版本中的@Async注释实现的方式中org.springframework.aop.interceptor.AsyncExecutionInterceptor#invoke这个里面没有用到lambda表达式，然而在Spring 5.x之后使用了lambda表达式来实现Callable接口。稍等几天，我将针对性对@Async做一个适配，届时将能够处理Spring各个版本的@Async注解。

**Comment by wushengqiang** [comment]
了解,感谢支持

**Comment by HaojunRen** [comment]
该问题已经解决，请使用如下的Agent
[discovery-agent.zip](https://github.com/Nepxion/Discovery/files/5246186/discovery-agent.zip)

**Comment by wushengqiang** [comment]
@HaojunRen 好的,感谢

**Comment by HaojunRen** [comment]
可以使用6.2.0的Agent，可以从Release Note里拿，或者自行编译也可以（根目录下mvn clean install）

**Comment by HaojunRen** [comment]
@wushengqiang 是否帮忙，在你的服务里帮忙验证一下新版agent的异步功能？

**Comment by wushengqiang** [comment]
我在代码里面测试了一下,用新版的agent可以正常的在spring @Aysnc中传递灰度

**Comment by HaojunRen** [comment]
[discovery-agent.zip](https://github.com/Nepxion/Discovery/files/5260222/discovery-agent.zip)

原来版本又发现了一个Bug。请用这个版本，经过反复测试，确认没有问题了
