### ISSUE TITLE
redis设置冲突

### ISSUE THREAD

**Issue by beesman182** [Nepxion/Discovery#121]
加依赖
```
        <dependency>
            <groupId>org.springframework.session</groupId>
            <artifactId>spring-session-data-redis</artifactId>
        </dependency>
```
加注解
`@EnableRedisHttpSession`
后discovery-plugin-config-center-starter-redis 就没法用了
冲突了

**Comment by HaojunRen** [comment]
discovery-plugin-config-center-starter-redis是社区贡献的，可能有不成熟的地方，如果有问题，你可以帮忙提交一个PR

你也可以选择Nacos或者Apollo做灰度订阅

**Comment by beesman182** [comment]
spring-session-data-redis 和 discovery-plugin-config-center-starter-redis中都定义了下面的Bean冲突了
public RedisMessageListenerContainer redisMessageListenerContainer()

**Comment by HaojunRen** [comment]
加个@ConditionalOnMissingBean试试，如果可行，请提交一个PR

**Comment by HaojunRen** [comment]
@Bean
    public RedisMessageListenerContainer redisMessageListenerContainer
改成
    @Bean
    public RedisMessageListenerContainer configMessageListenerContainer
试试

然后，在RedisConfigAdapter那里，改成

    @Autowired
    private RedisMessageListenerContainer configMessageListenerContainer;

**Comment by HaojunRen** [comment]
[redis.zip](https://github.com/Nepxion/Discovery/files/5474087/redis.zip)

请把附件2个类覆盖到相应位置，然后本地打包，试试看

**Comment by HaojunRen** [comment]
更新最新的代码，修复了该问题，请验证一下

**Comment by HaojunRen** [comment]
在Discovery根目录执行mvn clean install，然后在你的pom里把Discovery版本改成6.3.5-SNAPSHOT

**Comment by beesman182** [comment]
没有问题了。
