### ISSUE TITLE
failover->com.netflix.client.ClientException: Load balancer does not have available server for client: provider

### ISSUE THREAD

**Issue by daiwenlong** [Nepxion/Discovery#124]
调用链：gateway->service->provider

service 和 provider 都存在1.0 和 2.0 版本
都配置了failover

当 service ：3.0 provider ：3.0 都故意配错版本时

service调用provider  异常  com.netflix.client.ClientException: Load balancer does not have available server for client: provider

service 版本正常，provider版本不正常时可以failover   , 版本都不正常时不能failover,  如何解决？

**Comment by HaojunRen** [comment]
failover只能支持通过Header传递的模式
