### ISSUE TITLE
polaris 不开源码？

### ISSUE THREAD

**Issue by gravin** [Nepxion/Discovery#125]
polaris 有什么作用？看起来好像discovery就够了啊

**Comment by HaojunRen** [comment]
Polaris特色功能支持多云多活，此为商业性软件，不开源

**Comment by zwp201301** [comment]
> Polaris特色功能支持多云多活，此为商业性软件，不开源

中小公司，需要如何获取呢

**Comment by HaojunRen** [comment]
Polaris源码，价格6888元一套
