### ISSUE TITLE
多线程模式下, trace id不相同

### ISSUE THREAD

**Issue by ZhangNingPegasus** [Nepxion/Discovery#133]
服务A在thread或thread-pool模式下调用服务B， 此时，服务A的trace_id和服务B的trace_id不相同，是否需要设置什么参数？
![1](https://user-images.githubusercontent.com/40190761/103760373-f9e36580-504f-11eb-8258-cefb91f3e9e0.jpg)
![2](https://user-images.githubusercontent.com/40190761/103760377-fb149280-504f-11eb-8e0e-ba258e647ed7.jpg)

**Comment by HaojunRen** [comment]
TraceId不相同取决于第三方监控软件，是否对异步做了处理？如果用Jaeger，需要自己手工处理一下，源码里有。如果用SkyWalking，它对异步似乎支持的不够好

**Comment by ZhangNingPegasus** [comment]
项目使用的sleuth + zipkin做的链路跟踪，采取的是官方demo工程中的Open Feign例子，属于父子线程的调用方式，Discovery Agent也开启了MDC，依旧还是trace_id不相同
![1](https://user-images.githubusercontent.com/40190761/103848060-80de1f80-50dc-11eb-9ee3-e29680bc9065.jpg)
![2](https://user-images.githubusercontent.com/40190761/103848064-82a7e300-50dc-11eb-9c0b-ceb87d2cbf2d.png)

**Comment by HaojunRen** [comment]
这跟Nepxion没有关系的，你去掉它，问题也依旧

**Comment by HaojunRen** [comment]
traceid和mdc也没关系，slueth的异步方案，建议百度一下

**Comment by ZhangNingPegasus** [comment]
谢谢，问题已解决
