### ISSUE TITLE
网关直接使用Feign调用服务不能灰度

### ISSUE THREAD

**Issue by xiaoyangzhang** [Nepxion/Discovery#136]
根据Header头传递的方式实现了全链路蓝绿调用。
但是因为需要在网关中做一些权限校验，使用Feign的方式调用应用服务，做不到蓝绿：蓝绿两套环境在网关被随机路由调用了

**Comment by HaojunRen** [comment]
网关里内置Feign，不支持这个场景

**Comment by HaojunRen** [comment]
Spring Cloud Gateway上对Feign做蓝绿灰度，会出现重复路由的场景，前段时间尝试了一下，就放弃了，目前网关只做路由分发用了

**Comment by xiaoyangzhang** [comment]
> Spring Cloud Gateway上对Feign做蓝绿灰度，会出现重复路由的场景，前段时间尝试了一下，就放弃了，目前网关只做路由分发用了

重复路由是指网关的RouteFilter在Feign调用和正常路由都会执行吗？我自己根据Service依赖的源码和文档指南，在gateway上实现了一套网关Feign调用的蓝绿灰度

**Comment by HaojunRen** [comment]
好，如果可行，是否可以贡献给社区？
你在微信群或者钉钉群里么？

**Comment by HaojunRen** [comment]
在网关上引入discovery-plugin-strategy-starter-service，即它又是网关，又是普通的服务，是否可行？

**Comment by HaojunRen** [comment]
在网关上引入discovery-plugin-strategy-starter-service，即它又是网关，又是普通的服务，是否可行？

**Comment by HaojunRen** [comment]
你的方案还是风险比较大，我不清楚你的网关用的是Zuul还是Spring Cloud Gateway，如果前者，可能还好一点，如果是后者，可能会遇到困难，SCG是基于WebFlux异步，而Feign还是同步，那么全链路发布的时候，要把RouteFilter里的异步上下文转化成Feign中的同步上下文。同时按照Nepxion模型，Feign和SCG上下文分开维护，现在要合在一起用，会造成两个上下文混合在一起。我建议，对于权限此类的服务，不会频繁更改，可能不太有蓝绿灰度的场景

**Comment by xiaoyangzhang** [comment]
> 好，如果可行，是否可以贡献给社区？
> 你在微信群或者钉钉群里么？

**Comment by xiaoyangzhang** [comment]
> 你的方案还是风险比较大，我不清楚你的网关用的是Zuul还是Spring Cloud Gateway，如果前者，可能还好一点，如果是后者，可能会遇到困难，SCG是基于WebFlux异步，而Feign还是同步，那么全链路发布的时候，要把RouteFilter里的异步上下文转化成Feign中的同步上下文。同时按照Nepxion模型，Feign和SCG上下文分开维护，现在要合在一起用，会造成两个上下文混合在一起。我建议，对于权限此类的服务，不会频繁更改，可能不太有蓝绿灰度的场景

使用的是SCG，我大概描述一下自己的改造思路：SCG里进行Feign调用不能蓝绿灰度，是因为Feign请求里没有带n-d-version(这里以n-d-verison作示例描述)，所以复写RequestInterceptor接口的方法在Header里设置n-d-version，当进行Feign调用时可以传递n-d-version;
```java
Map<String, Collection<String>> headers = requestTemplate.headers();
            if (CollectionUtils.isEmpty(headers.get(DiscoveryConstant.N_D_VERSION))) {
                Map<String, String> headerMap = Maps.newHashMap();
                headerMap.put(contextRequestHeaders, gatewayStrategyContextHolder.getHeader(contextRequestHeaders));
                RuleEntity ruleEntity = pluginConfigParser.parse(rule);
                pluginAdapter.setLocalRule(ruleEntity);
                String routeVersion = strategyWrapper.getConditionBlueGreenRouteVersion(headerMap);
                if (StringUtils.isNotEmpty(routeVersion)) {
                    requestTemplate.header(DiscoveryConstant.N_D_VERSION, routeVersion);
                } else {
                    requestTemplate.header(DiscoveryConstant.N_D_VERSION, ruleEntity.getStrategyEntity()
                                                                                    .getVersionValue());
                }
            }
```
根据文档提示，继承DefaultDiscoveryEnabledStrategy并实现apply方法，在apply方法里判断服务列表的某个Server是否符合蓝绿灰度策略，符合策略的可以作为负载的路由节点
```java
@Override
    public boolean apply(Server server) {
        Map<String, String> headerMap = Maps.newHashMap();
        String headerVersion = gatewayStrategyContextHolder.getHeader(contextRequestHeaders);
        headerMap.put(contextRequestHeaders, headerVersion);
        pluginAdapter.setLocalRule(pluginConfigParser.parse(rule));
        String routeVersion = strategyWrapper.getConditionBlueGreenRouteVersion(headerMap);
        //灰度版本
        if (StringUtils.isNotBlank(headerVersion) && StringUtils.isNotBlank(routeVersion) && routeVersion.contains("gray")) {
            return true;
        }
        return true;
    }
```

**Comment by xiaoyangzhang** [comment]
> 好，如果可行，是否可以贡献给社区？
> 你在微信群或者钉钉群里么？

不在

**Comment by HaojunRen** [comment]
OK，基本可行，多测测，扫描文档中的微信二维码入群

**Comment by xiaoyangzhang** [comment]
> OK，基本可行，多测测，扫描文档中的微信二维码入群

已加入
