### ISSUE TITLE
关于灰度发布在同步调用过程中失效的2个疑问

### ISSUE THREAD

**Issue by ZhangNingPegasus** [Nepxion/Discovery#138]
SpringBoot版本:  2.3.7.RELEASE
SpringCloud版本: Hoxton.SR9
Nepxion Discovery版本: 6.5.0
网关版本: SpringCloud Gateway 2.2.6.RELEASE
注册中心版本: Consul 1.8.5
配置中心版本: Apollo 1.7.0
监控中心版本: Zipkin 2.2.6.RELEASE
Discovery Agent探针版本: 1.0.1
调用链：网关 -> 服务A -> 服务B

灰度发布的数据放置在Apollo中，只有网关订阅，整个调用链路采用请求头进行传输。
服务A采用Feign的方式同步调用服务B, 服务A始终能拿到网关传来的n-d-version请求头, 但是服务B在两种情况下会丢失，导致灰度发布在服务B中失效，具体情况如下。 

情况一: 
        同步调用过程中，也必须设置Discovery Agent，否则服务B始终会丢失请求头n-d-version（按照文档的说法，这种同步调用方式应该不需要设置探针），相关截图如下。
![1](https://user-images.githubusercontent.com/40190761/105115735-4fb21600-5b04-11eb-9368-556dc9cf2b18.png)
![2](https://user-images.githubusercontent.com/40190761/105115742-53459d00-5b04-11eb-9f0f-c42ddcebda0f.png)

情况二: 
        服务A和服务B都配置了Discovery Agent，B服务在第一次启动后的第一次调用中始终会丢失n-d-version，导致灰度发布在此次调用的服务B中失效；再在不做任何修改的情况下直接调用第二次，B服务就能正确拿到n-d-version的请求头，包括后续的调用过程都能拿到，相关截图如下。
![3](https://user-images.githubusercontent.com/40190761/105115762-5e98c880-5b04-11eb-970d-e62aa1f307cb.png)

**Comment by HaojunRen** [comment]
同步调用不需要设置Agent，你的截图我无法显示，可以加我微信1394997
