### ISSUE TITLE
能否加一个类似于spring-cloud-dependencies的版本控制依赖

### ISSUE THREAD

**Issue by IcebergXTY** [Nepxion/Discovery#139]
我们公司内部有一个统一的parent依赖，现在需要把Discovery所有的组件都声明一遍，实在太多了......而且后续如果你的组件有新增或修改，我们也要同步修改。

希望能加一个Discovery组件统一的版本控制

**Comment by HaojunRen** [comment]
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.nepxion</groupId>
                <artifactId>discovery</artifactId>
                <version>${discovery.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

**Comment by HaojunRen** [comment]
参考如下用法

https://gitee.com/nepxion/DiscoveryPlatform/blob/master/pom.xml
