### ISSUE TITLE
启动demo

### ISSUE THREAD

**Issue by shenzhuan** [Nepxion/Discovery#140]

**Comment by shenzhuan** [comment]
DiscoveryApplicationA1
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'configContextClosedHandler': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'AFeignImpl': Unsatisfied dependency expressed through field 'bFeign'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.nepxion.discovery.plugin.example.service.feign.BFeign': FactoryBean threw exception on object creation; nested exception is java.lang.NoClassDefFoundError: feign/hystrix/FallbackFactory$Default

**Comment by HaojunRen** [comment]
用DiscoveryGuide 6.x.x分支，master还不能用，对标Spring Cloud 2020

**Comment by shenzhuan** [comment]
哦 什么时候可以用了 准备直接用2020做一个商城 试试水

**Comment by HaojunRen** [comment]
除了Spring Cloud Alibaba之外，其它都可用，你自己可以排除

**Comment by shenzhuan** [comment]
Discovery里面的example不行吗 为什么要用DiscoveryGuide 项目  有什么不一样吗

**Comment by HaojunRen** [comment]
Discovery里面的example有点老，很多功能没有集成，也可以用

**Comment by shenzhuan** [comment]
Nacos started successfully in cluster mode. use external storage 
naocs启动了 但是service注册不上去 什么都没有改 启动了两个服务都这样
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([localhost:8848]) tried: ErrCode:500, ErrMsg:java.net.SocketTimeoutException: Read timed out

**Comment by HaojunRen** [comment]
Nacos运在本地，应该是standardalone模式，cluster模式可能会有问题
