### ISSUE TITLE
discovery仓库6.x.x分支discovery-springcloud-example-service#DiscoveryApplicationA1启动报错

### ISSUE THREAD

**Issue by MingIXu** [Nepxion/Discovery#145]
没改代码前报错：

`Error creating bean with name 'AFeignImpl': Unsatisfied dependency expressed through field 'bFeign'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'com.nepxion.discovery.plugin.example.service.feign.BFeign': Requested bean is currently in creation: Is there an unresolvable circular reference?`

去掉com.nepxion.discovery.plugin.example.service.feign.AFeignImpl中BFeign依赖后才能正常启动，改动代码如下：
```
 public class AFeignImpl extends AbstractFeignImpl implements AFeign {
    private static final Logger LOG = LoggerFactory.getLogger(AFeignImpl.class);

//    @Autowired
//    private BFeign bFeign;

    @Override
    public String invoke(@RequestBody String value) {
        value = doInvoke(value);
//        value = bFeign.invoke(value);

        LOG.info("调用路径：{}", value);

        return value;
    }
}
```

**Comment by HaojunRen** [comment]
版本降级到Hoxton.SR9，没这个问题

**Comment by HaojunRen** [comment]
原因是Sentinel不适配新版本的Spring Cloud
