### ISSUE TITLE
配置nepxion之后，微服务的/actuator监控接口调用出错！

### ISSUE THREAD

**Issue by apple987** [Nepxion/Discovery#147]
![image](https://user-images.githubusercontent.com/21330215/109262248-1f435300-77f9-11eb-8de8-87351f7150b0.png)

http://127.0.0.1:8082/actuator 这个接口可以访问成功，
但是具体访问http://127.0.0.1:8082/actuator/loggers接口时，什么也没返回，接口也不报错
8082是微服务order的端口，当order微服务排除掉nepxion插件，可以正常在monitor服务查看order服务的监控信息。
具体的系统代码在如下压缩文件中，请帮忙查看一下是order微服务哪里存在问题，谢谢！！！

[nacos-seata.zip](https://github.com/Nepxion/Discovery/files/6047722/nacos-seata.zip)

**Comment by HaojunRen** [comment]
6.7.0已解决这个问题，下周一发版

**Comment by apple987** [comment]
好的，👍

**Comment by HaojunRen** [comment]
6.7.0已经发布，请试用

**Comment by apple987** [comment]
已经测试，问题已经修复
