### ISSUE TITLE
路由控制开关不生效，设置为false之后应用无法启动

### ISSUE THREAD

**Issue by dearcode2018** [Nepxion/Discovery#152]
spring.application.strategy.control.enabled = false
在某些场景不需要路由策略，设置此开关无效，需要排除spring.factories自动配置的bean.

# 关闭discovery框架功能，排除自动配置类
spring: 
  autoconfigure:
    exclude: 
      - com.nepxion.discovery.plugin.configcenter.configuration.ConfigAutoConfiguration
      - com.nepxion.discovery.plugin.framework.configuration.PluginAutoConfiguration
      - com.nepxion.discovery.plugin.registercenter.eureka.configuration.EurekaAutoConfiguration
      - com.nepxion.discovery.plugin.strategy.configuration.StrategyAutoConfiguration
      - com.nepxion.discovery.plugin.strategy.service.configuration.ServiceStrategyAutoConfiguration
      -  com.nepxion.discovery.plugin.strategy.service.configuration.ServiceStrategyContextAutoConfiguration

**Comment by HaojunRen** [comment]
该开关的确不能关闭，就忽略这个开关存在吧。
不需要路由场景，即不传递任何路由Header，不配置任何策略即可，不影响任何TPS
