### ISSUE TITLE
超链接地址不正确

### ISSUE THREAD

**Issue by gzwxh** [Nepxion/Discovery#154]
访问:http://nepxion.gitee.io/discovery/#/?id=%e7%8e%af%e5%a2%83%e6%90%ad%e5%bb%ba
参考其中的例子进行操作,点击源码主页:Polaris源码主页  时,地址不正确,报错404

https://github.com/Nepxion/Polaris

**Comment by HaojunRen** [comment]
Polaris属商业框架

**Comment by gzwxh** [comment]
好的,谢谢
