### ISSUE TITLE
feign调用服务没有被version限制住

### ISSUE THREAD

**Issue by wangyi187571997** [Nepxion/Discovery#166]
我的cloud版本是Hoxton.SR3,Discovery版本是6.10.0,在gateway打上了n-d-version={"B":"gray"}的标签,打到了服务A上,这个服务A需要调用服务B,这个时候服务B的version是"dev".理论上不会调用通过,但是正常调用,没有被Discovery的版本号拦截规则拦截下来,正常访问了.我打印了A收到的header信息,确认收到了n-d-version={"B":"gray"}

**Comment by HaojunRen** [comment]
version是dev？是不是跟region搞在一起了？

**Comment by wangyi187571997** [comment]
不是的,因为目前需要做指定用户在指定的某几个服务做灰度访问,正常的全部走正常服务.所以在网关gateway统一判断用户是否灰度,从而灰度的增加灰度的n-d-version信息,正常的用户为n-d-version=prod.本来想用env做,但是env不支持某几个服务特殊处理,所以现在采用version.

**Comment by HaojunRen** [comment]
提供更详细的截图，规则配置，调用截图等

**Comment by wangyi187571997** [comment]
![image](https://user-images.githubusercontent.com/36835438/122561818-e283bc00-d074-11eb-8a68-214fcc764186.png)
这是B服务的nacos注册信息,version版本是dev
![image](https://user-images.githubusercontent.com/36835438/122561965-0f37d380-d075-11eb-873d-8c5b134b907f.png)
这是A服务调用方准备执行的时候的request里面的header头信息,里面携带n-d-version={"zjf-oms":"gray"}
![image](https://user-images.githubusercontent.com/36835438/122562249-72296a80-d075-11eb-9a89-6fb409682a92.png)
这是调用成功的提示,理论上不允许调用成功,但是这里feign还是调用不属于这个指定version的服务

**Comment by HaojunRen** [comment]
打印Header的图，截屏还不够全面

**Comment by wangyi187571997** [comment]
blade-auth:bearer xxxxxx
user-agent:PostmanRuntime/7.28.0
accept:*/*
postman-token:dc88a08c-22e7-4588-95bf-3a02c4eb1a23
accept-encoding:gzip, deflate, br
n-d-version:{"zjf-oms":"gray"}
n-d-service-group:dev
n-d-service-type:gateway
n-d-service-id:blade-gateway
n-d-service-address:10.8.0.102:80
n-d-service-version:dev
n-d-service-region:default
n-d-service-env:dev
n-d-service-zone:default
forwarded:proto=http;host=localhost;for="0:0:0:0:0:0:0:1:54751"
x-forwarded-for:0:0:0:0:0:0:0:1
x-forwarded-proto:http
x-forwarded-prefix:/blade-user
x-forwarded-port:80
x-forwarded-host:localhost
host:10.8.0.102:8087
sw8:
sw8-correlation:
sw8-x:0-
content-length:0
上面是header信息

**Comment by HaojunRen** [comment]
你打印的header是网关日子，你要把zjf-oms这个服务的header发上来。补充一句，是否用了异步？

**Comment by wangyi187571997** [comment]
我给的是调用方的header头信息,目前是三个服务,gateway,user,oms.顺序是gateway转发到user,user通过feign调用oms.这里是通过feign调用的,没有用到异步.
n-d-service-address:10.8.0.102:8087
n-d-service-env:dev
n-d-service-group:dev
n-d-service-id:blade-user
n-d-service-region:default
n-d-service-type:service
n-d-service-version:dev
n-d-service-zone:default
accept:*/*
sw8:
sw8-correlation:
sw8-x:0-
host:10.8.0.102:8903
connection:Keep-Alive
accept-encoding:gzip
user-agent:okhttp/3.14.5
这是oms收到的header信息

**Comment by HaojunRen** [comment]
综上分析

调用路径：gateway -> blade-user -> zjf-oms
gateway已经发出了n-d-version:{"zjf-oms":"gray"}给user服务
blade-user服务上并没有显示n-d-version:{"zjf-oms":"gray"}，所以blade-user没有收到网关发来的n-d-version

gateway是spring cloud gateway，还是zuul？是否在gateway上启用了hystrix?

**Comment by wangyi187571997** [comment]
blade-user收到了n-d-version:{"zjf-oms":"gray"},我在最开始给的那个
blade-auth:bearer xxxxxx
user-agent:PostmanRuntime/7.28.0
accept:/
postman-token:dc88a08c-22e7-4588-95bf-3a02c4eb1a23
accept-encoding:gzip, deflate, br
n-d-version:{"zjf-oms":"gray"}
n-d-service-group:dev
n-d-service-type:gateway
n-d-service-id:blade-gateway
n-d-service-address:10.8.0.102:80
n-d-service-version:dev
n-d-service-region:default
n-d-service-env:dev
n-d-service-zone:default
forwarded:proto=http;host=localhost;for="0:0:0:0:0:0:0:1:54751"
x-forwarded-for:0:0:0:0:0:0:0:1
x-forwarded-proto:http
x-forwarded-prefix:/blade-user
x-forwarded-port:80
x-forwarded-host:localhost
host:10.8.0.102:8087
sw8:
sw8-correlation:
sw8-x:0-
content-length:0
这个就是在blade-user服务打印出来的header信息,gateway是spring cloud gateway

**Comment by HaojunRen** [comment]
上面这个信息，并不是blade-user的信息，因为
n-d-service-type:gateway - 当前服务是网关
n-d-service-id:blade-gateway - 当前服务名是blade-gateway 

这个依旧是网关上打印的信息

**Comment by wangyi187571997** [comment]
但是这个是我在blade-user的controller里面把request当做参数,方法内部直接打印request的请求头获取的,获取的请求头对象就是这个.
gateway请求头是没有带参数的,我在gateway新增了拦截器,判断用户是灰度的,在header头加上n-d-version
![image](https://user-images.githubusercontent.com/36835438/122568557-74db8e00-d07c-11eb-89a0-daf19351f248.png)

**Comment by HaojunRen** [comment]
你为何要再去处理一遍Header信息呢？

**Comment by HaojunRen** [comment]
你加我微信 1394997

**Comment by wangyi187571997** [comment]
感谢微信帮忙已解决,hystrix线程池问题,增加了Discovery Agent问题解决成功
