### ISSUE TITLE
spring cloud 引入问题

### ISSUE THREAD

**Issue by renyp-veteran** [Nepxion/Discovery#169]
您好！
       最近公司项目（spring cloud项目 注册中心：nacos、 配置中心：apollo、网关：gateway）引入灰度发布，看到了Nepxion Discovery项目很感兴趣。尝试在已有项目中引入，导入依赖后抛出异常

因为本身项目用nacos注册中心，所以关于nacos依赖已经存在，暂时回避和discovery引入nacos冲突，我使用了

`spring:
  main:
    allow-bean-definition-overriding: true`

来回避冲突问题。
但是启动项目还是抛出了一下异常

`java.lang.IllegalStateException: Error processing condition on com.alibaba.cloud.nacos.discovery.reactive.NacosReactiveDiscoveryClientConfiguration.nacosReactiveDiscoveryClient`

`Caused by: java.lang.IllegalStateException: @ConditionalOnMissingBean did not specify a bean using type, name or annotation and the attempt to deduce the bean's type failed`

`Caused by: org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanTypeDeductionException: Failed to deduce bean type for com.alibaba.cloud.nacos.discovery.reactive.NacosReactiveDiscoveryClientConfiguration.nacosReactiveDiscoveryClient`

`Caused by: java.lang.NoClassDefFoundError: org/springframework/cloud/client/discovery/ReactiveDiscoveryClient`

`Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.client.discovery.ReactiveDiscoveryClient`

**Comment by renyp-veteran** [comment]
引入的依赖

![微信截图_20210707183429](https://user-images.githubusercontent.com/58755705/124745876-dc397f00-df52-11eb-9dc5-8721a192c8c6.png)
![微信截图_20210707183444](https://user-images.githubusercontent.com/58755705/124745886-dd6aac00-df52-11eb-8187-fd05387386bc.png)

**Comment by HaojunRen** [comment]
你使用的Spring Cloud是哪个版本？

**Comment by HaojunRen** [comment]
H版以及以下版本，Nepxion只支持Ribbon负载均衡，不支持Reactor负载均衡，2020以上的版本才支持

**Comment by renyp-veteran** [comment]
> H版以及以下版本，Nepxion只支持Ribbon负载均衡，不支持Reactor负载均衡，2020以上的版本才支持

好的，我对比一下版本，感谢

**Comment by renyp-veteran** [comment]
公司用的是Spring cloud G版，怎样解决上面提到的引入Nepxion Discovery的冲突问题？

**Comment by HaojunRen** [comment]
F，G，H都可以使用6.11.0

**Comment by renyp-veteran** [comment]
引入后，项目启动报错是怎么回事




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nepxion/Discovery"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 晚上6:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nepxion/Discovery] spring cloud 引入问题 (#169)





 
F，G，H都可以使用6.11.0

**Comment by renyp-veteran** [comment]
我的pom文件


<?xml version="1.0" encoding="UTF-8"?&gt;
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"&gt;
   <modelVersion&gt;4.0.0</modelVersion&gt;

   <artifactId&gt;kcwl-app-gateway</artifactId&gt;
   <packaging&gt;jar</packaging&gt;

   <parent&gt;
      <groupId&gt;org.springframework.boot</groupId&gt;
      <artifactId&gt;spring-boot-starter-parent</artifactId&gt;
      <version&gt;2.1.10.RELEASE</version&gt;
   </parent&gt;

   <name&gt;kcwl-app-gateway</name&gt;
   <properties&gt;
      <project.build.sourceEncoding&gt;UTF-8</project.build.sourceEncoding&gt;
      <project.reporting.outputEncoding&gt;UTF-8</project.reporting.outputEncoding&gt;
      <java.version&gt;1.8</java.version&gt;
      <spring-cloud.version&gt;Greenwich.SR5</spring-cloud.version&gt;
      <lombok.version&gt;1.18.6</lombok.version&gt;
      <kcwl-framework.version&gt;1.1.6-SNAPSHOT</kcwl-framework.version&gt;
      <spring.cloud.openfeign.version&gt;2.2.5.RELEASE</spring.cloud.openfeign.version&gt;

      <discovery.version&gt;6.10.0</discovery.version&gt;

      <!-- Spring Cloud Hoxton compatible versions --&gt;
<!--      <spring.cloud.version&gt;Hoxton.SR11</spring.cloud.version&gt;--&gt;
      <spring.cloud.alibaba.version&gt;2.2.5.RELEASE</spring.cloud.alibaba.version&gt;
      <spring.boot.version&gt;2.1.10.RELEASE</spring.boot.version&gt;
   </properties&gt;

   <dependencies&gt;
      <dependency&gt;
         <groupId&gt;org.springframework.boot</groupId&gt;
         <artifactId&gt;spring-boot-configuration-processor</artifactId&gt;
         <optional&gt;true</optional&gt;
      </dependency&gt;
      <dependency&gt;
         <groupId&gt;org.springframework.cloud</groupId&gt;
         <artifactId&gt;spring-cloud-starter-gateway</artifactId&gt;
         <version&gt;2.2.0.RELEASE</version&gt;
      </dependency&gt;

      <!--<dependency&gt;
         <groupId&gt;com.alibaba.nacos</groupId&gt;
         <artifactId&gt;nacos-client</artifactId&gt;
         <version&gt;0.4.0</version&gt;
      </dependency&gt;--&gt;
      <!--<dependency&gt;
         <groupId&gt;com.alibaba.cloud</groupId&gt;
         <artifactId&gt;spring-cloud-starter-alibaba-sentinel</artifactId&gt;
         <version&gt;2.1.0.RELEASE</version&gt;
      </dependency&gt;
      <dependency&gt;
         <groupId&gt;com.alibaba.cloud</groupId&gt;
         <artifactId&gt;spring-cloud-alibaba-sentinel-gateway</artifactId&gt;
         <version&gt;2.1.0.RELEASE</version&gt;
       </dependency&gt;
      <dependency&gt;
         <groupId&gt;com.alibaba.csp</groupId&gt;
         <artifactId&gt;sentinel-transport-simple-http</artifactId&gt;
         <version&gt;1.6.3</version&gt;
      </dependency&gt;
      <dependency&gt;
         <groupId&gt;com.alibaba.csp</groupId&gt;
         <artifactId&gt;sentinel-spring-cloud-gateway-adapter</artifactId&gt;
         <version&gt;1.6.3</version&gt;
      </dependency&gt;--&gt;
        <!--end sentinel--&gt;
      <dependency&gt;
         <groupId&gt;org.springframework.boot</groupId&gt;
         <artifactId&gt;spring-boot-starter-webflux</artifactId&gt;
      </dependency&gt;

      <dependency&gt;
         <groupId&gt;org.springframework.boot</groupId&gt;
         <artifactId&gt;spring-boot-starter-actuator</artifactId&gt;
      </dependency&gt;

      <dependency&gt;
         <groupId&gt;com.google.code.gson</groupId&gt;
         <artifactId&gt;gson</artifactId&gt;
         <version&gt;2.8.5</version&gt;
      </dependency&gt;

      <dependency&gt;
         <groupId&gt;com.alibaba</groupId&gt;
         <artifactId&gt;fastjson</artifactId&gt;
         <version&gt;1.2.47</version&gt;
      </dependency&gt;

      <dependency&gt;
         <groupId&gt;org.projectlombok</groupId&gt;
         <artifactId&gt;lombok</artifactId&gt;
         <version&gt;${lombok.version}</version&gt;
      </dependency&gt;

      <dependency&gt;
         <groupId&gt;com.kcwl.framework</groupId&gt;
         <artifactId&gt;kcwl-apollo-client</artifactId&gt;
         <version&gt;${kcwl-framework.version}</version&gt;
      </dependency&gt;
        <dependency&gt;
            <groupId&gt;mysql</groupId&gt;
            <artifactId&gt;mysql-connector-java</artifactId&gt;
            <version&gt;5.1.43</version&gt;
            <scope&gt;runtime</scope&gt;
        </dependency&gt;
        <dependency&gt;
            <groupId&gt;org.springframework.boot</groupId&gt;
            <artifactId&gt;spring-boot-starter-data-jpa</artifactId&gt;
        </dependency&gt;
        <dependency&gt;
            <groupId&gt;org.springframework.boot</groupId&gt;
            <artifactId&gt;spring-boot-starter-test</artifactId&gt;
        </dependency&gt;
      <dependency&gt;
         <groupId&gt;commons-io</groupId&gt;
         <artifactId&gt;commons-io</artifactId&gt;
         <version&gt;2.6</version&gt;
      </dependency&gt;
      <dependency&gt;
         <groupId&gt;org.testng</groupId&gt;
         <artifactId&gt;testng</artifactId&gt;
         <version&gt;6.14.3</version&gt;
         <scope&gt;test</scope&gt;
      </dependency&gt;
      <dependency&gt;
         <groupId&gt;com.alibaba.cloud</groupId&gt;
         <artifactId&gt;spring-cloud-alibaba-nacos-discovery</artifactId&gt;
         <version&gt;2.1.1.RELEASE</version&gt;
      </dependency&gt;
      <dependency&gt;
         <groupId&gt;com.github.vladimir-bukhtoyarov</groupId&gt;
         <artifactId&gt;bucket4j-core</artifactId&gt;
         <version&gt;6.2.0</version&gt;
      </dependency&gt;

      <dependency&gt;
         <groupId&gt;org.springframework.cloud</groupId&gt;
         <artifactId&gt;spring-cloud-dependencies</artifactId&gt;
         <version&gt;${spring-cloud.version}</version&gt;
         <type&gt;pom</type&gt;
         <scope&gt;import</scope&gt;
      </dependency&gt;

      <dependency&gt;
         <groupId&gt;org.springframework.boot</groupId&gt;
         <artifactId&gt;spring-boot-dependencies</artifactId&gt;
         <version&gt;${spring.boot.version}</version&gt;
         <type&gt;pom</type&gt;
         <scope&gt;import</scope&gt;
      </dependency&gt;

      <dependency&gt;
         <groupId&gt;com.nepxion</groupId&gt;
         <artifactId&gt;discovery</artifactId&gt;
         <version&gt;${discovery.version}</version&gt;
         <type&gt;pom</type&gt;
         <scope&gt;import</scope&gt;
      </dependency&gt;

      <!-- 1.注册中心插件 --&gt;
      <dependency&gt;
         <groupId&gt;com.nepxion</groupId&gt;
         <artifactId&gt;discovery-plugin-register-center-starter-nacos</artifactId&gt;
         <version&gt;${discovery.version}</version&gt;
      </dependency&gt;

      <!-- 2.配置中心插件 --&gt;
      <dependency&gt;
         <groupId&gt;com.nepxion</groupId&gt;
         <artifactId&gt;discovery-plugin-config-center-starter-apollo</artifactId&gt;
         <version&gt;${discovery.version}</version&gt;
      </dependency&gt;

      <!-- 3.管理中心插件 （非必须）--&gt;
      <dependency&gt;
         <groupId&gt;com.nepxion</groupId&gt;
         <artifactId&gt;discovery-plugin-admin-center-starter</artifactId&gt;
         <version&gt;${discovery.version}</version&gt;
      </dependency&gt;

      <!-- 4.网关策略编排插件 --&gt;
      <dependency&gt;
         <groupId&gt;com.nepxion</groupId&gt;
         <artifactId&gt;discovery-plugin-strategy-starter-gateway</artifactId&gt;
         <version&gt;${discovery.version}</version&gt;
      </dependency&gt;
   </dependencies&gt;

   <dependencyManagement&gt;
      <dependencies&gt;

      </dependencies&gt;
   </dependencyManagement&gt;

   <build&gt;
      <finalName&gt;${project.artifactId}</finalName&gt;
      <plugins&gt;
         <plugin&gt;
            <groupId&gt;org.springframework.boot</groupId&gt;
            <artifactId&gt;spring-boot-maven-plugin</artifactId&gt;
         </plugin&gt;
      </plugins&gt;
   </build&gt;

   <repositories&gt;
     
   </repositories&gt;

</project&gt;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nepxion/Discovery"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 晚上6:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nepxion/Discovery] spring cloud 引入问题 (#169)





 
F，G，H都可以使用6.11.0

**Comment by renyp-veteran** [comment]
这个是我最新的pom文件，刚才那个有点儿问题


<?xml version="1.0" encoding="UTF-8"?&gt;
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"&gt;
   <modelVersion&gt;4.0.0</modelVersion&gt;

   <artifactId&gt;kcwl-app-gateway</artifactId&gt;
   <packaging&gt;jar</packaging&gt;

   <parent&gt;
      <groupId&gt;org.springframework.boot</groupId&gt;
      <artifactId&gt;spring-boot-starter-parent</artifactId&gt;
      <version&gt;2.1.10.RELEASE</version&gt;
   </parent&gt;

   <name&gt;kcwl-app-gateway</name&gt;
   <properties&gt;
      <project.build.sourceEncoding&gt;UTF-8</project.build.sourceEncoding&gt;
      <project.reporting.outputEncoding&gt;UTF-8</project.reporting.outputEncoding&gt;
      <java.version&gt;1.8</java.version&gt;
      <spring-cloud.version&gt;Greenwich.SR5</spring-cloud.version&gt;
      <lombok.version&gt;1.18.6</lombok.version&gt;
      <kcwl-framework.version&gt;1.1.6-SNAPSHOT</kcwl-framework.version&gt;
      <spring.cloud.openfeign.version&gt;2.2.5.RELEASE</spring.cloud.openfeign.version&gt;

      <discovery.version&gt;6.10.0</discovery.version&gt;

      <!-- Spring Cloud Hoxton compatible versions --&gt;
<!--      <spring.cloud.version&gt;Hoxton.SR11</spring.cloud.version&gt;--&gt;
      <spring.cloud.alibaba.version&gt;2.2.5.RELEASE</spring.cloud.alibaba.version&gt;
      <spring.boot.version&gt;2.1.10.RELEASE</spring.boot.version&gt;
   </properties&gt;

   <dependencies&gt;
      <dependency&gt;
         <groupId&gt;org.springframework.boot</groupId&gt;
         <artifactId&gt;spring-boot-configuration-processor</artifactId&gt;
         <optional&gt;true</optional&gt;
      </dependency&gt;
      <dependency&gt;
         <groupId&gt;org.springframework.cloud</groupId&gt;
         <artifactId&gt;spring-cloud-starter-gateway</artifactId&gt;
         <version&gt;2.2.0.RELEASE</version&gt;
      </dependency&gt;

      <!--<dependency&gt;
         <groupId&gt;com.alibaba.nacos</groupId&gt;
         <artifactId&gt;nacos-client</artifactId&gt;
         <version&gt;0.4.0</version&gt;
      </dependency&gt;--&gt;
      <!--<dependency&gt;
         <groupId&gt;com.alibaba.cloud</groupId&gt;
         <artifactId&gt;spring-cloud-starter-alibaba-sentinel</artifactId&gt;
         <version&gt;2.1.0.RELEASE</version&gt;
      </dependency&gt;
      <dependency&gt;
         <groupId&gt;com.alibaba.cloud</groupId&gt;
         <artifactId&gt;spring-cloud-alibaba-sentinel-gateway</artifactId&gt;
         <version&gt;2.1.0.RELEASE</version&gt;
       </dependency&gt;
      <dependency&gt;
         <groupId&gt;com.alibaba.csp</groupId&gt;
         <artifactId&gt;sentinel-transport-simple-http</artifactId&gt;
         <version&gt;1.6.3</version&gt;
      </dependency&gt;
      <dependency&gt;
         <groupId&gt;com.alibaba.csp</groupId&gt;
         <artifactId&gt;sentinel-spring-cloud-gateway-adapter</artifactId&gt;
         <version&gt;1.6.3</version&gt;
      </dependency&gt;--&gt;
        <!--end sentinel--&gt;
      <dependency&gt;
         <groupId&gt;org.springframework.boot</groupId&gt;
         <artifactId&gt;spring-boot-starter-webflux</artifactId&gt;
      </dependency&gt;

      <dependency&gt;
         <groupId&gt;org.springframework.boot</groupId&gt;
         <artifactId&gt;spring-boot-starter-actuator</artifactId&gt;
      </dependency&gt;

      <dependency&gt;
         <groupId&gt;com.google.code.gson</groupId&gt;
         <artifactId&gt;gson</artifactId&gt;
         <version&gt;2.8.5</version&gt;
      </dependency&gt;

      <dependency&gt;
         <groupId&gt;com.alibaba</groupId&gt;
         <artifactId&gt;fastjson</artifactId&gt;
         <version&gt;1.2.47</version&gt;
      </dependency&gt;

      <dependency&gt;
         <groupId&gt;org.projectlombok</groupId&gt;
         <artifactId&gt;lombok</artifactId&gt;
         <version&gt;${lombok.version}</version&gt;
      </dependency&gt;

      <dependency&gt;
         <groupId&gt;com.kcwl.framework</groupId&gt;
         <artifactId&gt;kcwl-apollo-client</artifactId&gt;
         <version&gt;${kcwl-framework.version}</version&gt;
      </dependency&gt;
        <dependency&gt;
            <groupId&gt;mysql</groupId&gt;
            <artifactId&gt;mysql-connector-java</artifactId&gt;
            <version&gt;5.1.43</version&gt;
            <scope&gt;runtime</scope&gt;
        </dependency&gt;
        <dependency&gt;
            <groupId&gt;org.springframework.boot</groupId&gt;
            <artifactId&gt;spring-boot-starter-data-jpa</artifactId&gt;
        </dependency&gt;
        <dependency&gt;
            <groupId&gt;org.springframework.boot</groupId&gt;
            <artifactId&gt;spring-boot-starter-test</artifactId&gt;
        </dependency&gt;
      <dependency&gt;
         <groupId&gt;commons-io</groupId&gt;
         <artifactId&gt;commons-io</artifactId&gt;
         <version&gt;2.6</version&gt;
      </dependency&gt;
      <dependency&gt;
         <groupId&gt;org.testng</groupId&gt;
         <artifactId&gt;testng</artifactId&gt;
         <version&gt;6.14.3</version&gt;
         <scope&gt;test</scope&gt;
      </dependency&gt;
      <dependency&gt;
         <groupId&gt;com.alibaba.cloud</groupId&gt;
         <artifactId&gt;spring-cloud-alibaba-nacos-discovery</artifactId&gt;
         <version&gt;2.1.1.RELEASE</version&gt;
      </dependency&gt;
      <dependency&gt;
         <groupId&gt;com.github.vladimir-bukhtoyarov</groupId&gt;
         <artifactId&gt;bucket4j-core</artifactId&gt;
         <version&gt;6.2.0</version&gt;
      </dependency&gt;



      <dependency&gt;
         <groupId&gt;org.springframework.boot</groupId&gt;
         <artifactId&gt;spring-boot-dependencies</artifactId&gt;
         <version&gt;${spring.boot.version}</version&gt;
         <type&gt;pom</type&gt;
         <scope&gt;import</scope&gt;
      </dependency&gt;

      <dependency&gt;
         <groupId&gt;com.nepxion</groupId&gt;
         <artifactId&gt;discovery</artifactId&gt;
         <version&gt;${discovery.version}</version&gt;
         <type&gt;pom</type&gt;
         <scope&gt;import</scope&gt;
      </dependency&gt;

      <!-- 1.注册中心插件 --&gt;
      <dependency&gt;
         <groupId&gt;com.nepxion</groupId&gt;
         <artifactId&gt;discovery-plugin-register-center-starter-nacos</artifactId&gt;
         <version&gt;${discovery.version}</version&gt;
      </dependency&gt;

      <!-- 2.配置中心插件 --&gt;
      <dependency&gt;
         <groupId&gt;com.nepxion</groupId&gt;
         <artifactId&gt;discovery-plugin-config-center-starter-apollo</artifactId&gt;
         <version&gt;${discovery.version}</version&gt;
      </dependency&gt;

      <!-- 3.管理中心插件 （非必须）--&gt;
      <dependency&gt;
         <groupId&gt;com.nepxion</groupId&gt;
         <artifactId&gt;discovery-plugin-admin-center-starter</artifactId&gt;
         <version&gt;${discovery.version}</version&gt;
      </dependency&gt;

      <!-- 4.网关策略编排插件 --&gt;
      <dependency&gt;
         <groupId&gt;com.nepxion</groupId&gt;
         <artifactId&gt;discovery-plugin-strategy-starter-gateway</artifactId&gt;
         <version&gt;${discovery.version}</version&gt;
      </dependency&gt;
   </dependencies&gt;

   <dependencyManagement&gt;
      <dependencies&gt;
         <dependency&gt;
            <groupId&gt;org.springframework.cloud</groupId&gt;
            <artifactId&gt;spring-cloud-dependencies</artifactId&gt;
            <version&gt;${spring-cloud.version}</version&gt;
            <type&gt;pom</type&gt;
            <scope&gt;import</scope&gt;
         </dependency&gt;
      </dependencies&gt;
   </dependencyManagement&gt;

   <build&gt;
      <finalName&gt;${project.artifactId}</finalName&gt;
      <plugins&gt;
         <plugin&gt;
            <groupId&gt;org.springframework.boot</groupId&gt;
            <artifactId&gt;spring-boot-maven-plugin</artifactId&gt;
         </plugin&gt;
      </plugins&gt;
   </build&gt;

   <repositories&gt;
     。。。
   </repositories&gt;

</project&gt;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nepxion/Discovery"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 晚上6:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nepxion/Discovery] spring cloud 引入问题 (#169)





 
F，G，H都可以使用6.11.0

**Comment by HaojunRen** [comment]
Gitee Issue上我已经回答。6.x.x只支持Ribbon，不支持Spring Cloud Loadbalancer，后者只在7.x.x支持
