### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by qeprwjcgya** [Nepxion/Discovery#173]
如果封装一些业务性框架的东西，相信商业版本更有市场。比如：es,MQ,分布式事务等。这样小型公司如果你这套框架，就专注写业务就行了，养一个水平一般的架构师熟悉你的框架，这样成本就低了，小公司就更乐意用您的商业版本了。纯属个人想法。

**Comment by HaojunRen** [comment]
感谢建议，对于MQ，`https://github.com/Nepxion/DiscoveryContrib`，粗浅的做了一下，未最终完成，其它部分也未涉及。你提到的这些组件，在蓝绿发布上的行为收敛有点困难，所以没继续下去。如果你感兴趣，可以参与贡献
