### ISSUE TITLE
想问一下，我能基于6.12版做开源吗？

### ISSUE THREAD

**Issue by fengzhongye** [Nepxion/Discovery#176]
框架名称 | 框架版本 | 支持Spring Cloud版本 | 使用许可
-- | -- | -- | --
Discovery | 1.x.x ~ 6.x.x | Camden ~ Hoxton | 开源，永久免费
DiscoveryX | 7.x.x | 202x | 闭源，商业许可

因为 DiscoveryX 7.x.x 版闭源的原因，所以我在 6.12 的版本上开发了支持 spring cloud 202x 的版本，想问一下我能开源出来吗？

**Comment by HaojunRen** [comment]
你可以随意改源码，也可以在公司内部随意用，但不建议你开源出来

**Comment by fengzhongye** [comment]
好的。非常感激这个框架，给了我很多启发，希望这个框架越做越好
