### ISSUE TITLE
Please open a GitHub Security Advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [Nepxion/Discovery#196]
Hello,

I'm an independent security researcher performing security research under the [GitHub Security Lab Bug Bounty Program](https://securitylab.github.com/). I believe I may have found a security vulnerability in this project.

Please open a security advisory against this repository so we can privately discuss the details. This advisory can be opened by a user with admin permissions on this repository.

https://github.com/Nepxion/Discovery/security/advisories 

Vulnerability disclosure will occur on Mar 12, 2023.

Alternatively, if you provide me with a list of admins on this project, I've written up the disclosure here for you to review:
https://github.com/JLLeitschuh/security-research/security/advisories/GHSA-22cq-8f5q-p5g2

**Comment by JLLeitschuh** [comment]
By closing this issue without response, please understand this issue will be publicly disclosed without a fix.

**Comment by HaojunRen** [comment]
```
public static <T> T fromYaml(String yaml, Class<T> clazz) {
    Yaml snakeYaml = new Yaml();
    return snakeYaml.loadAs(yaml, clazz);
}
```
If we change above code with
```
public static <T> T fromYaml(String yaml, Class<T> clazz) {
    Yaml snakeYaml = new Yaml(new SafeConstructor());
    return snakeYaml.loadAs(yaml, clazz);
}
```
It will impact function with following exception
```
Exception in thread "main" could not determine a constructor for the tag tag:yaml.org,2002:com.nepxion.discovery.common.entity.ConditionStrategy
 in 'string', line 1, column 1:
    service:
    ^
```

**Comment by JLLeitschuh** [comment]
Then you need to specify an allowed list of classes that are safe to deserialize to

**Comment by JLLeitschuh** [comment]
What YAML are you attempting to deserialize? Can you provide an example?

**Comment by HaojunRen** [comment]
Please refer to the example with

https://github.com/Nepxion/Discovery/blob/6.x.x/discovery-commons/discovery-common/src/test/java/com/nepxion/discovery/common/ConditionStrategyYamlTest.java

**Comment by HaojunRen** [comment]
> Then you need to specify an allowed list of classes that are safe to deserialize to

Would you please give an example to set the allowed list?

**Comment by HaojunRen** [comment]
Fix it with https://github.com/Nepxion/Discovery/blob/6.x.x/discovery-commons/discovery-common/src/main/java/com/nepxion/discovery/common/yaml/YamlSafeConstructor.java
