### ISSUE TITLE
请教如何异步通过feign指定n-d-version调用目标版本的微服务

### ISSUE THREAD

**Issue by LuckyBillX** [Nepxion/Discovery#201]

**Comment by HaojunRen** [comment]
使用DiscoveryAgent，wiki上有使用说明

**Comment by LuckyBillX** [comment]
![image](https://user-images.githubusercontent.com/2239473/222305508-69932774-e494-4599-a827-c73294f50326.png)
我这样测试完后没有效果,请问这样使用正确吗?

**Comment by LuckyBillX** [comment]
Map<String, String> attributes = new HashMap<String, String>();
        attributes.put("n-d-version", "1.8");
        MyContext.getCurrentContext().setAttributes(attributes);
        feign.test(123L,5,"balance test",null);

//        Thread thread=new Thread(new Runnable() {
//            @Override
//            public void run() {
//                feign.test(123L,5,"balance test",null);
//            }
//        });
//        thread.start();

我这样测试完后没有效果,请问这样使用是正确的吗?
