### ISSUE TITLE
spring.cloud.consul.discovery.prefer-ip-address 配置失效

### ISSUE THREAD

**Issue by sail-y** [Nepxion/Discovery#41]
今天在基于Nepxion Discovery注册的时候，因为机器上有多网卡的关系，有几个是虚拟机的虚拟网卡，在注册consul的时候选用了虚拟网卡的ip。检查配置发现并没有配置

```properties
spring.cloud.consul.discovery.prefer-ip-address=true
```

在`ConsulApplicationContextInitializer.java`类中，发现一行代码

```java
ConsulDiscoveryProperties consulDiscoveryProperties = (ConsulDiscoveryProperties) bean;
consulDiscoveryProperties.setPreferIpAddress(true);
```

这里将配置写死了，建议大佬去除此配置，让用户可以自由配置`spring.cloud.consul.discovery.prefer-ip-address`  😄

**Comment by sail-y** [comment]
说是这么说，但是怪怪的

**Comment by HaojunRen** [comment]
那好，我开放出来，许多IP相关的功能，请谨慎使用
