### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by panjianping** [Nepxion/Discovery#46]
1. rule.xml 规则文件需要在每个微服务下存在一份吗？（如服务 网关1->A1->B1->C1，对应的同一个规则文件是否需要在 网关1,A1,B1,C1下都存在）
2. discovery-console-desktop 一定要和一个注册中心一起使用吗？

**Comment by HaojunRen** [comment]
1. 可以分开，也可以合在一起，建议后者，全局配置，具体见文档
2. 必须连配置中心。desktop，它会console获取配置中心上的服务列表
