### ISSUE TITLE
4.1.2版本的discovery-plugin-starter-eureka引入后启动报错

### ISSUE THREAD

**Issue by pengjieran** [Nepxion/Discovery#5]
如果只引入discovery-plugin-starter-eureka，启动会报错，读不到${swagger.service.description}这个值，我猜测应该是依赖的某个swagger没有引入，我参考的是discovery-springcloud-example下的配置，本来是想在zuul引入的。

**Comment by Nepxion** [comment]
example下bootstrap.properties

# Swagger config
swagger.service.base.package=com.nepxion.discovery.plugin.admincenter.endpoint
swagger.service.description=Admin Center Restful APIs
swagger.service.version=1.0.0
swagger.service.license=Apache License 2.0
swagger.service.license.url=http://www.apache.org/licenses/LICENSE-2.0
swagger.service.contact.name=Haojun Ren
swagger.service.contact.url=https://github.com/Nepxion/Discovery
swagger.service.contact.email=1394997@qq.com

你是否引入了？

**Comment by Nepxion** [comment]
请加我微信 1394997，详细探讨
