### ISSUE TITLE
示例工程好像没有一个是完整的可运行工程？

### ISSUE THREAD

**Issue by zrweng** [Nepxion/Discovery#53]
想快速看到Discovery效果,都需要自己建工程引入依赖，有点麻烦，既然是示例工程能提供完整的演示示例吗？

**Comment by HaojunRen** [comment]
所有的例子都需要全部跑起来，可能需要一个性能很好的机器，这样才能模拟出一个复杂的灰度发布场景

**Comment by zrweng** [comment]
机器不是问题，能否提供完整Hello word Demo？:)

**Comment by HaojunRen** [comment]
下面带example的都是示例额
