### ISSUE TITLE
问一下5.0.0版本，对Greenwich版本的支持，有发版计划吗？

### ISSUE THREAD

**Issue by haycco** [Nepxion/Discovery#59]
如题哈，什么时候会发布至Maven中央仓库呢，对webflux reactor的支持有开发计划吗

**Comment by HaojunRen** [comment]
和Spring cloud alibaba正式版一起发布，大概是下周

**Comment by haycco** [comment]
Hello， @HaojunRen 发版计划delay了啊，想问一下，[discovery-plugin-strategy-starter-service](https://github.com/Nepxion/Discovery/tree/master/discovery-plugin-strategy-starter-service) 还有webflux版吗？我看都还是依赖的spring-boot-starter-web，对webflux没有支持呢

**Comment by HaojunRen** [comment]
已经发布

**Comment by yangchengwin** [comment]
webflux版没找到呢，Greenwich版的gateway集成失败呢

**Comment by HaojunRen** [comment]
Spring Cloud Gateway就是WebFlux版
