### ISSUE TITLE
按照readme步骤测试,报错.

### ISSUE THREAD

**Issue by df270464278** [Nepxion/Discovery#6]
### 服务注册过滤的操作演示
黑/白名单的IP地址注册的过滤
- 在rule.xml把本地IP地址写入到相应地方
- 启动DiscoveryApplicationA1.java
- 抛出禁止注册的异常，即本地服务受限于黑名单的IP地址列表，不会注册到服务注册发现中心；白名单操作也是如此，不过逻辑刚好相反.
演示启动DiscoveryApplicationA1.java,报以下异常
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method hystrixGatewayFilterFactory in org.springframework.cloud.gateway.config.GatewayAutoConfiguration$HystrixConfiguration required a bean of type 'org.springframework.web.reactive.DispatcherHandler' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.web.reactive.DispatcherHandler' in your configuration.
注册中心用的eureka,启动是成功的.

**Comment by Nepxion** [comment]
支持Spring Cloud Gateway，我还在进行中，你先用zuul

**Comment by df270464278** [comment]
这个意思是,你现在项目默认使用的gateway,我需要把项目里面的网关由gateway换成zuul吗?

**Comment by Nepxion** [comment]
不是，支持Spring Cloud Api Gateway目前我还在开发中。你报的这个错误是因为Spring Cloud Api Gateway不支持Spring boot web starter和Swagger。

**Comment by df270464278** [comment]
明白了,多谢,我再试试

**Comment by Nepxion** [comment]
问题解决了

**Comment by df270464278** [comment]
辛苦了

**Comment by xushuyi1002** [comment]
问题怎么解决的呢？
![image](https://user-images.githubusercontent.com/35679460/54575285-77c71e80-4a2e-11e9-8a93-ec431b612db1.png)
