### ISSUE TITLE
现在支持从nacos config获取.properties类型配置文件吗?

### ISSUE THREAD

**Issue by shangkun** [Nepxion/Discovery#60]
现在支持从nacos config获取.properties类型配置文件吗?,项目需要动态的配置一些除了nepxion相关配置之外的配置"如redis",但是nepxion好像只支持xml,json类型配置,且我把当前properties修改为xml也是无法初始化redis的

**Comment by HaojunRen** [comment]
把规则文件xml或者json放在nacos里即可，这三个配置中心存放的可以是key->xml内容
