### ISSUE TITLE
问题：请求头带了version，version是以前app的版本号，现在影响到了服务请求链路，请问有什么办法可以解决？

### ISSUE THREAD

**Issue by panjianping** [Nepxion/Discovery#61]
版本：4.8.4.1

**Comment by HaojunRen** [comment]
version是这个框架的保留字，把你们的version字段前面加前缀吧。这个的确当时是设计的不够恰当

**Comment by panjianping** [comment]
现在是我们以前版本的app请求头就已经带了version，如果使用了 Discovery ，那以前的 app 请求服务接口就会有问题了，不知道有没有地方可以 version 保留字的？

**Comment by HaojunRen** [comment]
我这边可以改，但改了以后，会影响到其它公司的使用，所以是两难。你可以自己改源码，这个默认写起到代码里了，你自己找一下

**Comment by panjianping** [comment]
好的，现在已经找到修改的地方了。

**Comment by HaojunRen** [comment]
下个版本会重构掉，改成x-d-version

**Comment by HaojunRen** [comment]
新版本已经发布，version改成了n-d-version
