### ISSUE TITLE
示例演示中版本权重访问规则改变存在问题

### ISSUE THREAD

**Issue by lw5946** [Nepxion/Discovery#62]
要想达到文中所述
> 操作的逻辑：B服务1.0的版本向A服务提供10%流量，B服务1.1的版本向A服务提供90%流量

按照我的理解, 新的版本权重规则应该如下:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rule>
    <discovery>
        <weight>
            <service consumer-service-name="discovery-springcloud-example-a" provider-service-name="discovery-springcloud-example-b" provider-weight-value="1.0=10;1.1=90"/>
        </weight>
    </discovery>
</rule>
```
而且, post的请求地址应该是 `http://localhost:1100/config/update-sync` 和 `http://localhost:1101/config/update-sync`
其中, consumer应该是`a`, provider应该是`b`, 不知道我理解的是否对?

**Comment by lw5946** [comment]
按照此逻辑, 在示例演示中区域权重规则改变的灰度发布服务中, 应该请求的地址是 `http://localhost:1100/config/update-sync` 和 `http://localhost:1101/config/update-sync`.

不知道我的理解是否对?

**Comment by HaojunRen** [comment]
规则是作用在消费端，即a上，b上无效，因为是发生在a调用b时候的负载均衡策略上
