### ISSUE TITLE
swagger 在 2.x 版本 不支持  webflux

### ISSUE THREAD

**Issue by foxiswho** [Nepxion/Discovery#67]
在 webflux 中 报错，因为 swagger 2.x 不支持 webflux
discovery-plugin-admin-center/src/main/java/com/nepxion/discovery/plugin/admincenter/configuration/SwaggerConfiguration.java

**Comment by HaojunRen** [comment]
该问题在上个月已经得到了修正，在Spring Cloud Gateway里应该不会有问题，请问你用的是哪个版本？

**Comment by HaojunRen** [comment]
估计在你的Webflux里引入了spring-webmvc的包，这是不允许的，会引起冲突。

还有个方案，加上swagger.service.enabled=false试试

**Comment by foxiswho** [comment]
4.1.2

好的

**Comment by HaojunRen** [comment]
有4.1.2这个版本么？

**Comment by foxiswho** [comment]
写错了。是 5.1.2


刚  去掉 spring-webmvc 包 正常了，谢谢
