### ISSUE TITLE
pluginAdapter 获取元数据中版本问题

### ISSUE THREAD

**Issue by jackorjack** [Nepxion/Discovery#68]
## 版本
 - nepxion 5.1.2
 - nacos  1.0.1
 - springcloud  F版
## 实现AbstractDiscoveryEnabledStrategy
在实现AbstractDiscoveryEnabledStrategy 后使用  String version = pluginAdapter.getServerMetadata(server).get(DiscoveryConstant.VERSION);
获取版本号，好像一直获取的都是本地版本号，想知道是设计就是如此，还是一个bug,
还有一个问题String dynamicVersion = pluginAdapter.getDynamicVersion()；是获取的zuul 网关的动态版本，还是服务的提供端的版本

**Comment by HaojunRen** [comment]
请不要用dynamicVersion，这块功能是有风险的。因为修改了动态版本，注册中心metadata不会改变。
pluginAdapter.getServerMetadata(server).get(DiscoveryConstant.VERSION);是有问题的。通过路由方式来决定调用路径吧。参考https://github.com/Nepxion/DiscoveryGray
