### ISSUE TITLE
https://github.com/Nepxion/DiscoveryGray  example中动态修改版本找不到服务

### ISSUE THREAD

**Issue by jackorjack** [Nepxion/Discovery#69]
在运行example中zuul灰度路由，动态修改了service中的版本，当路由动态修改的版本时会com.netflix.client.ClientException: Load balancer does not have available server for client: discovery-gray-service-b

**Comment by HaojunRen** [comment]
建议不要用动态版本，该功能会被废弃掉。通过规则（rule.xml）配置中心或者策略（header）来实现
