### ISSUE TITLE
关于错误注册的实现方案

### ISSUE THREAD

**Issue by hi-sb** [Nepxion/Discovery#71]
看了下面关于错误注册的方案，用黑白名单其实并不好。结合一下以前我们的做法，consul 本身有acl token这个特性，也就是说通过consul 可以实现费token赋予某个节点的读或者写的权限，来控制，比如 sit/service1 这是一个sit 的服务节点。那么sit 环境分配到了一个acl token 叫做 0x1782173 ,那么这个token 具有这个服务的读权限则可以发现这个服务。具有这个节点的写权限则可以注册这个服务。同理 通过consul的 acl token 可以控制 各环境，甚至是一个环境下每一个token 能发现哪些服务，能注册哪些服务都是可以控制的。

我这边，以前实现过一次，但是一些原因那个代码不能拿出来。在这里提供一个思路，希望有帮助，谢谢！

**Comment by HaojunRen** [comment]
我集成的不仅仅是Consul，还有Nacos，Eureka，Zookeeper。我需要统一的解决方案

**Comment by HaojunRen** [comment]
Consul Token机制并不好，它是随机生成的，我们要做到更安全的方式，例如token三个月更新一次，一旦更新，consul上注册的服务全部都要手工更新一遍。请问你们是怎么管理的？
