### ISSUE TITLE
关于在网关路由处增加根据group的路由策略

### ISSUE THREAD

**Issue by joeylearning** [Nepxion/Discovery#75]
现在的DefaultZuulStrategyRouteFilter没有支持通过group的路由策略，不知道作者的考虑是什么，其实这个问题也是接着上面的问题，开发测试环境的隔离和互用问题
[https://github.com/Nepxion/Discovery/issues/74](url)

**Comment by HaojunRen** [comment]
该需求可以考虑通过region来实现

**Comment by joeylearning** [comment]
> 该需求可以考虑通过region来实现

确实实现了，就感觉region的概念跟开始理解的有出入，这样使用之后感觉group和region的概念有所冲突；如果能在规则这个层面支持优先级的调用感觉更合理，现在的规则需要配置比较多，毕竟策略需要通过header实现，有些情况下会比较麻烦一点。
