### ISSUE TITLE
GatewayStrategyContext数据污染问题

### ISSUE THREAD

**Issue by wmj765** [Nepxion/Discovery#78]
1.我在用GatewayStrategyContext存储变量的时候，在初始filter设置了值，在拿到response后即使清空了threadlocal中的值，下次请求还会拿到上一次的结果。
2.由于gateway采用的是reactor框架，很多请求线程是一个，是否会造成数据污染

**Comment by HaojunRen** [comment]
你用的是什么版本？

**Comment by HaojunRen** [comment]
你最好不要去操作框架内核的上下文存储，这是为灰度路由准备的，如果由于业务需要保存上下文，请自行写一个上下文存储吧

**Comment by wmj765** [comment]
嗯，谢谢，我用其他的cache来保存上下文了，zuul的时候用threadlocal不会出现这个问题。查资料有reactor context来取代threadlocal。

**Comment by HaojunRen** [comment]
你说的没错，webflux下threadlocal处理起来有点难度的。GatewayStrategyContext我只存储了ServerWebExchange对象，该对象是提供给Ribbon用的。你自己的Filter跟Discovery框架里的Filter并不是运行在同一个子线程里。在9月28日发布的5.4.0版本中我在Discovery框架里的Filter里暴露出一个方法
    protected void extendFilter(ServerHttpRequest.Builder requestBuilder, Boolean gatewayHeaderPriority, Boolean gatewayOriginalHeaderIgnored) {

    }
在这个方法里，requestBuilder可以自行放入业务的Header之类的参数。如果这种方式还是不满足，你可以继承我的DefaultGatewayStrategyRouteFilter，扩展
    @Override
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        super.filter(xxx);
        // 自己的逻辑
    }

对于DefaultGatewayStrategyRouteFilter的处理，我加了@ConditionalOnMissingBean
    @Bean
    @ConditionalOnMissingBean
    public GatewayStrategyRouteFilter gatewayStrategyRouteFilter() {
        return new DefaultGatewayStrategyRouteFilter();
    }

**Comment by HaojunRen** [comment]
嗯，谢谢，我用其他的cache来保存上下文了，zuul的时候用threadlocal不会出现这个问题。查资料有reactor context来取代threadlocal。
----------------------------------------------------------------
其实，你自定义的filter，完全不需要cache，因为每个filter全程都带着ServerWebExchange，在里面可以获取到Request对象

**Comment by HaojunRen** [comment]
清除上下文也已经支持，业务端的Configuration加上下面这行即可，更好的方式还在研究中
```java
@Bean
public GatewayStrategyClearFilter gatewayStrategyContextClearFilter() {
    return new DefaultGatewayStrategyClearFilter();
}
```

**Comment by wmj765** [comment]
好的，感谢你的解答，参考你的方案已经解决

**Comment by yusu123** [comment]
> 好的，感谢你的解答，参考你的方案已经解决



> ## 嗯，谢谢，我用其他的cache来保存上下文了，zuul的时候用threadlocal不会出现这个问题。查资料有reactor context来取代threadlocal。
> 其实，你自定义的filter，完全不需要cache，因为每个filter全程都带着ServerWebExchange，在里面可以获取到Request对象

想问下你是怎么用其他的cache来保存上下文了的？
