### ISSUE TITLE
discovery-guide-service引用nacos的配置问题

### ISSUE THREAD

**Issue by lijinfangljf** [Nepxion/Discovery#79]
应用discovery-guide-service中，如何配置才取到nacos配置中心的配置。

**Comment by lijinfangljf** [comment]
nacos注册服务是没问题

**Comment by lijinfangljf** [comment]
![image](https://user-images.githubusercontent.com/56444067/66659395-0541b880-ec76-11e9-9c77-de2a4b4b4b5e.png)
![image](https://user-images.githubusercontent.com/56444067/66659455-1d193c80-ec76-11e9-88ac-8b7e3eccae39.png)

![image](https://user-images.githubusercontent.com/56444067/66659540-45a13680-ec76-11e9-9e48-fe691c2e0f80.png)
![image](https://user-images.githubusercontent.com/56444067/66659581-5baef700-ec76-11e9-92c9-b284b8cf6f7c.png)

错误信息

**Comment by HaojunRen** [comment]
业务配置，需要引入nacos config相关包，请查看相关官网

**Comment by lijinfangljf** [comment]
参考你的com/alibaba/cloud/examples/Application.java
类NacosConfigManager找不到

**Comment by HaojunRen** [comment]
这是阿里官方的例子，请联系他们解决
