### ISSUE TITLE
公共配置是否可以提取到一个文件中

### ISSUE THREAD

**Issue by sglmsn** [Nepxion/Discovery#81]
现在貌似每个项目都维护着一些同样的配置, 是否可以将他们提取到一个文件或者项目中进行维护, 这样改起来比较简单,现在改都是用的全局替换..

**Comment by HaojunRen** [comment]
公共配置基于Group的，一个Group下面有一群微服务，所有的微服务指向同一个公共配置

**Comment by sglmsn** [comment]
不是说这个, 是说基础配置,比如
middleware.host=localhost

# Nacos config for discovery
spring.cloud.nacos.discovery.server-addr=${middleware.host}:8848
spring.cloud.nacos.discovery.metadata.group=discovery-guide-group
spring.cloud.nacos.discovery.metadata.version=1.0

# Consul config for discovery
spring.cloud.consul.host=${middleware.host}
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.tags=group=discovery-guide-group,version=1.0

# Eureka config for discovery
eureka.client.serviceUrl.defaultZone=http://${middleware.host}:9528/eureka/
eureka.instance.metadataMap.group=discovery-guide-group
eureka.instance.metadataMap.version=1.0

# Ribbon config
ribbon.ConnectTimeout=60000
ribbon.ReadTimeout=60000
ribbon.maxAutoRetries=3
ribbon.maxAutoRetriesNextServer=3
ribbon.okToRetryOnAllOperations=true


这些貌似都是一样的配置,把他们提取出来

**Comment by HaojunRen** [comment]
这些配置是Spring Cloud相关配置，原本怎么配置就怎么来
