### ISSUE TITLE
考虑将开发中的代码更新为 SNAPSHOT 版本

### ISSUE THREAD

**Issue by RobinGG** [Nepxion/Discovery#83]
### 环境
- discovery.version: 5.5.2

### 问题描述

今天在尝试通过 discovery-springcloud-example-gateway 示例搭建一个 Demo 服务。然后发现在 `String environment = pluginAdapter.getServerEnvironment(server);` 报错。查看接口类，发现没有这个接口，但是 example 里面确实存在这个接口。版本号也符合，都是 5.5.2。进一步查看后发现是昨天新提交的代码（咋就这么巧），但是版本号并没有更新为 5.5.3-SNAPSHOT，就导致了代码不一致的情况出现

### 期望

在一个版本正式发布以后，后续的新功能开发版本号应该更新，比如 5.5.2-RELEASE  -->  5.5.3-SNAPSHOT

**Comment by HaojunRen** [comment]
里面是6.0.0-SNAPSHOT，你带源码工程引入吧，目前在等待一个第三方包更新，暂时无法发布新版本



---原始邮件---
发件人: "Robin Gong"<notifications@github.com&gt;
发送时间: 2019年11月22日(星期五) 下午4:47
收件人: "Nepxion/Discovery"<Discovery@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Nepxion/Discovery] 考虑将开发中的代码更新为 SNAPSHOT 版本 (#83)



环境
  
discovery.version: 5.5.2 
 
问题描述
 
今天在尝试通过 discovery-springcloud-example-gateway 示例搭建一个 Demo 服务。然后发现在 String environment = pluginAdapter.getServerEnvironment(server); 报错。查看接口类，发现没有这个接口，但是 example 里面确实存在这个接口。版本号也符合，都是 5.5.2。进一步查看后发现是昨天新提交的代码（咋就这么巧），但是版本号并没有更新为 5.5.3-SNAPSHOT，就导致了代码不一致的情况出现
 
期望
 
在一个版本正式发布以后，后续的新功能开发版本号应该更新，比如 5.5.2-RELEASE  --&gt;  5.5.3-SNAPSHOT

**Comment by RobinGG** [comment]
更新到 5.5.3 以后确实没有问题了
不过我观察到 5.x.x 的分支代码仍然是在一个 RELEASE 的版本
我还是建议：如果 5.x.x 分支仍然考虑有新功能开发的话，希望可以在 SNAPSHOT 分支开发
