### ISSUE TITLE
有讨论群吗

### ISSUE THREAD

**Issue by hsoftxl** [Nepxion/Discovery#85]

**Comment by HaojunRen** [comment]
看文档介绍里面有微信号：1394997




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"huisongyang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月25日(星期三) 下午2:41
收件人:&nbsp;"Nepxion/Discovery"<Discovery@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Nepxion/Discovery] 有讨论群吗 (#85)
