### ISSUE TITLE
DiscoveryClientDecorator can not be Autowired

### ISSUE THREAD

**Issue by hhtower** [Nepxion/Discovery#86]
version 5.5.10

Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.nepxion.discovery.plugin.framework.decorator.DiscoveryClientDecorator' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

**Comment by HaojunRen** [comment]
I have ran Nepxion DiscoveryGuide a moment ago, not found this issue as you pointed

**Comment by hhtower** [comment]
> I have ran Nepxion DiscoveryGuide a moment ago, not found this issue as you pointed
I just used

**Comment by hhtower** [comment]
> I have ran Nepxion DiscoveryGuide a moment ago, not found this issue as you pointed

Maven dependencies
discovery-plugin-starter-eureka and discovery-plugin-strategy-starter-gateway.
and then I Autowired the DiscoveryClientDecorator in custom DefaultGatewayStrategyRouteFilter，then ran faild.

**Comment by hhtower** [comment]
> I have ran Nepxion DiscoveryGuide a moment ago, not found this issue as you pointed

Maven dependencies
discovery-plugin-starter-eureka and discovery-plugin-strategy-starter-gateway.
and then I Autowired the DiscoveryClientDecorator in custom DefaultGatewayStrategyRouteFilter，then ran faild.

**Comment by HaojunRen** [comment]
It works fine, refer to following picture:
![图片](https://user-images.githubusercontent.com/42354711/71808691-67f5f500-30a9-11ea-86fe-f22be8f16128.png)

**Comment by hhtower** [comment]
> It works fine, refer to following picture:
> ![图片](https://user-images.githubusercontent.com/42354711/71808691-67f5f500-30a9-11ea-86fe-f22be8f16128.png)

like this
![image](https://user-images.githubusercontent.com/6490052/71875265-de086380-315e-11ea-951e-2297e1886e77.png)
![image](https://user-images.githubusercontent.com/6490052/71875301-eeb8d980-315e-11ea-8d99-9bef6a5a12cd.png)

**Comment by hhtower** [comment]
> It works fine, refer to following picture:
> ![图片](https://user-images.githubusercontent.com/42354711/71808691-67f5f500-30a9-11ea-86fe-f22be8f16128.png)

ran faild， refer to following picture based Nepxion DiscoveryGuide discovery-guide-gateway .

![image](https://user-images.githubusercontent.com/6490052/71875649-c67daa80-315f-11ea-8215-445e206fb11d.png)

**Comment by HaojunRen** [comment]
注入的应该是DiscoveryClient，而不是它的装饰类

**Comment by HaojunRen** [comment]
注入的应该是DiscoveryClient，而不是它的装饰类
