### ISSUE TITLE
为何不基于eureka做灰度呢？

### ISSUE THREAD

**Issue by whfcomm** [Nepxion/Discovery#9]
为何不基于eureka（注册中心）做灰度呢？
这样每个服务都要去做配置，必须要搞清楚每个服务对应的消费者与生产
如果服务多，消费者也可能是生产者，这就感觉很麻烦了。
如果是在eureka（注册中心）做的话，注册中心肯定知道谁是谁，
谁得版本是多少，只有关注消费者即可，你要消费的在我的规则内就给你消费，不是就不允许你消费，不是挺好的

**Comment by Nepxion** [comment]
您的问题挺好，但是如果换成Consul或者甚至是Zookeeper呢？Eureka未来没有2.0版本了

**Comment by whfcomm** [comment]
后来我想想，贵团队应该是想到其他的注册中心的原因了，但是目前的方式对于服务较多的情况，会比较繁琐

**Comment by Nepxion** [comment]
是的。未来阿里巴巴Nasco很有可能会成主流，所以我的方案不能仅仅局限在Eureka上，同时如果按照你的想法，在Eureka服务上做的话，则会更加简单

**Comment by whfcomm** [comment]
那也许可以拜读一下你们的代码，单独对eureka进行开发^_^
