### ISSUE TITLE
ServerWebExchange对象在线程切换时丢失

### ISSUE THREAD

**Issue by VangelisHaha** [Nepxion/Discovery#92]
环境：SpringCloud ：Finchley  
Discovery：4.13.5 版本匹配
pom依赖检查无错误
启动项目
* gateway
* eureka
* apollo
* service-a_1.0,service-a_1.1（显示名）
* auth

问题：
在集成测试sevice-a 时使用Header 参数 指定了 n-d-version: {"service-a":"1.1"}
对应eurekametadata也指定了对应version 和group
实际结果版本指定规则未生效

于是乎一路Debug
~~~java
@Override
    public String getHeader(String name) {
       // 检查到此处发现从线程中获取ServerWebExchange 为null，排查无果
        ServerWebExchange exchange = getExchange();
        if (exchange == null) {
            LOG.warn("The ServerWebExchange object is lost for thread switched, or it is got before context filter probably");

            return null;
        }
        return exchange.getRequest().getHeaders().getFirst(name);
    }

~~~
如上所示，导致Header 中n-d-version 参数获取不到，作者大大这是为啥呀

**Comment by VangelisHaha** [comment]
我正在做的事情是使用传递Header从而版本匹配的灰度路由策略

**Comment by VangelisHaha** [comment]
补充说明：我debug先在下方代码处`AbstractGatewayStrategyRouteFilter`
~~~java
    @Override
   // 此处filter 中的exchange 为完整的请求数据也，仔细排查过这里还有n-d-version 参数
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        // 把ServerWebExchange放入ThreadLocal中
        //  GatewayStrategyContext.getCurrentContext()  debug看此处为null，导致后面的全部拿不到了
        GatewayStrategyContext.getCurrentContext().setExchange(exchange);

        String routeVersion = getRouteVersion();
        String routeRegion = getRouteRegion();
        String routeAddress = getRouteAddress();
        String routeVersionWeight = getRouteVersionWeight();
        String routeRegionWeight = getRouteRegionWeight();
~~~

**Comment by HaojunRen** [comment]
因为你可能用了Hystrix线程池隔离模式，请参考DiscoveryGuide的README

**Comment by VangelisHaha** [comment]
感谢回答，此问题已经排查发现问题所在，我正在将网关端全链路路由策略的灰度发布规则放入Apollo中，发现Apollo只支持维护 properties 即为 key->value 类似<br>
我在其他issue中找到您说可以使用 key -xml 方式放入配置中心即可，但是我查阅源码实在不知道key 该怎么定义，它是否是`strategy`=xml配置/json配置 ？

**Comment by HaojunRen** [comment]
是的。请在Discovery首页找一下，有Apollo如何配置的截图和说明文字

**Comment by VangelisHaha** [comment]
感谢作者的回答，已经配置好了。但是我请求网关然后转发到我的服务，最终我使用传递Header从而版本匹配 未生效，我确保我已经启动过DiscoveryGuide 进行过测试，查看过文档。
