### ISSUE TITLE
ZuulFilter 中远程调用，header中上传n-d-version，策略不生效

### ISSUE THREAD

**Issue by young-pastor** [Nepxion/Discovery#93]

**Comment by ht-coder-wu** [comment]
调试发现 可能由于 yml文件配置服务元数据导致。如果使用 guide中 bootstrap.properties 配置的 eureka.instance.metadataMap.version=1.0 header中上传n-d-version生效，使用 application.yml 中`eureka:
     instance:
        metadata-map:
           version: 1.0`  header中上传n-d-version不生效。  感觉像是yml文件格式不兼容导致的

**Comment by HaojunRen** [comment]
最后解决了么

**Comment by ht-coder-wu** [comment]
@HaojunRen 最后解决了 应该问题定位到的还是我上面描述的部分，在yml文件中是idea自动提示的是叫metadata-map 而properties文件中是叫metadataMap  改成放到properties 或者yml文件中改成metadataMap都可以
