### ISSUE TITLE
关于Jaeger无法记录dubbo链路的问题

### ISSUE THREAD

**Issue by lougb** [Nepxion/Discovery#95]
当我通过网关调取RestFul接口，而接口内部采用Dubbo调取内部子服务时，Jaeger无法记录dubbo调取过程，目前想到的办法是采用埋点将调取结果展示在span中，求教是不是我的配置有问题？还是别的原因导致无法全链路跟踪？

**Comment by HaojunRen** [comment]
本框架是基于Spring Cloud，不涉及Dubbo，老外不会去支持Dubbo的，需要自己自行实现
