### ISSUE TITLE
想问一下，为啥配置中心没有支持consul

### ISSUE THREAD

**Issue by orange-form** [Nepxion/Discovery#98]
您好，

目前配置中心支持了nacos、apollo和redis。想了解一下，为啥注册中心支持了consul，而配置中心没有支持呢？谢谢。

Stephen

**Comment by HaojunRen** [comment]
是的，目前的确不支持，社区同学们对Consul做配置中心的需求好像没有。如果你愿意，要么commit一把？

**Comment by orange-form** [comment]
@HaojunRen 
好的，我先学习一下。非常喜欢您开发的框架，有点儿相见恨晚的感觉。我们计划集成到我们的微服务中台化代码生成器中。
另外解释一下为啥配置中心要支持consul，主要原因是，Prometheus对nacos的注册中心支持不好，需要自己去参考consul的config-discovery-adaptor，模拟写出对nacos的支持。鉴于我们目前的阶段，所以我们才决定同时支持consul作为注册中心，既然consul也支持配置中心，所以我们就全都支持了。

**Comment by HaojunRen** [comment]
慎重考虑用Consul作为注册中心和配置中心
