### ISSUE TITLE
使用nacos最新版本1.3.0不能推送路由策略

### ISSUE THREAD

**Issue by allen-kaiser-cai** [Nepxion/Discovery#99]
@HaojunRen 你好，
我最新在学习Discovery开源框架，在使用DiscoveryGuide来测试时，发现如果安装了最新的Nacos 1.3.0版本，我在Nacos上配置了路由策略，始终无法推送成功。然后我重新安装了1.1.4版本的Nacos，这样所有的推送测试就都正常了。麻烦你帮忙看看是什么原因？谢谢

**Comment by HaojunRen** [comment]
Nacos 1.3.0刚出来，还没测试过

**Comment by allen-kaiser-cai** [comment]
好的，非常感谢你的答复。我再重新安装最新的Nacos 1.3.0试试，谢谢！
